
pub mod kana {
    #[allow(dead_code)]
    pub struct Kana {
        pub romaji: &'static str,
        pub kana: &'static str
    }
    
    #[allow(dead_code)]
    pub const HIRAGANA: [Kana; 46] = [
        Kana { romaji: "a", kana: "あ" },
        Kana { romaji: "i", kana: "い" },
        Kana { romaji: "u", kana: "う" },
        Kana { romaji: "e", kana: "え" },
        Kana { romaji: "o", kana: "お" },
        Kana { romaji: "ka", kana: "か" },
        Kana { romaji: "ki", kana: "き" },
        Kana { romaji: "ku", kana: "く" },
        Kana { romaji: "ke", kana: "け" },
        Kana { romaji: "ko", kana: "こ" },
        Kana { romaji: "sa", kana: "さ" },
        Kana { romaji: "shi", kana: "し" },
        Kana { romaji: "su", kana: "す" },
        Kana { romaji: "se", kana: "せ" },
        Kana { romaji: "so", kana: "そ" },
        Kana { romaji: "ta", kana: "た" },
        Kana { romaji: "chi", kana: "ち" },
        Kana { romaji: "tsu", kana: "つ" },
        Kana { romaji: "te", kana: "て" },
        Kana { romaji: "to", kana: "と" },
        Kana { romaji: "na", kana: "な" },
        Kana { romaji: "ni", kana: "に" },
        Kana { romaji: "nu", kana: "ぬ" },
        Kana { romaji: "ne", kana: "ね" },
        Kana { romaji: "no", kana: "の" },
        Kana { romaji: "ha", kana: "は" },
        Kana { romaji: "hi", kana: "ひ" },
        Kana { romaji: "fu", kana: "ふ" },
        Kana { romaji: "he", kana: "へ" },
        Kana { romaji: "ho", kana: "ほ" },
        Kana { romaji: "ma", kana: "ま" },
        Kana { romaji: "mi", kana: "み" },
        Kana { romaji: "mu", kana: "む" },
        Kana { romaji: "me", kana: "め" },
        Kana { romaji: "mo", kana: "も" },
        Kana { romaji: "ya", kana: "や" },
        Kana { romaji: "yu", kana: "ゆ" },
        Kana { romaji: "yo", kana: "よ" },
        Kana { romaji: "ra", kana: "ら" },
        Kana { romaji: "ri", kana: "り" },
        Kana { romaji: "ru", kana: "る" },
        Kana { romaji: "re", kana: "れ" },
        Kana { romaji: "ro", kana: "ろ" },
        Kana { romaji: "wa", kana: "わ" },
        Kana { romaji: "wo", kana: "を" },
        Kana { romaji: "n", kana: "ん" }
    ];

    #[allow(dead_code)]
    pub const KATAKANA: [Kana; 46] = [
        Kana { romaji: "a", kana: "ア" },
        Kana { romaji: "i", kana: "イ" },
        Kana { romaji: "u", kana: "ウ" },
        Kana { romaji: "e", kana: "エ" },
        Kana { romaji: "o", kana: "オ" },
        Kana { romaji: "ka", kana: "カ" },
        Kana { romaji: "ki", kana: "キ" },
        Kana { romaji: "ku", kana: "ク" },
        Kana { romaji: "ke", kana: "ケ" },
        Kana { romaji: "ko", kana: "コ" },
        Kana { romaji: "sa", kana: "サ" },
        Kana { romaji: "shi", kana: "シ" },
        Kana { romaji: "su", kana: "ス" },
        Kana { romaji: "se", kana: "セ" },
        Kana { romaji: "so", kana: "ソ" },
        Kana { romaji: "ta", kana: "タ" },
        Kana { romaji: "chi", kana: "チ" },
        Kana { romaji: "tsu", kana: "ツ" },
        Kana { romaji: "te", kana: "テ" },
        Kana { romaji: "to", kana: "ト" },
        Kana { romaji: "na", kana: "ナ" },
        Kana { romaji: "ni", kana: "ニ" },
        Kana { romaji: "nu", kana: "ヌ" }, 
        Kana { romaji: "ne", kana: "ネ" },
        Kana { romaji: "no", kana: "ノ" },
        Kana { romaji: "ha", kana: "ハ" },
        Kana { romaji: "hi", kana: "ヒ" },
        Kana { romaji: "fu", kana: "フ" },
        Kana { romaji: "he", kana: "ヘ" },
        Kana { romaji: "ho", kana: "ホ" },
        Kana { romaji: "ma", kana: "マ" },
        Kana { romaji: "mi", kana: "ミ" },
        Kana { romaji: "mu", kana: "ム" },
        Kana { romaji: "me", kana: "メ" },
        Kana { romaji: "mo", kana: "モ" },
        Kana { romaji: "ya", kana: "ヤ" },
        Kana { romaji: "yu", kana: "ユ" },
        Kana { romaji: "yo", kana: "ヨ" },
        Kana { romaji: "ra", kana: "ラ" },
        Kana { romaji: "ri", kana: "リ" },
        Kana { romaji: "ru", kana: "ル" },
        Kana { romaji: "re", kana: "レ" },
        Kana { romaji: "ro", kana: "ロ" },
        Kana { romaji: "wa", kana: "ワ" },
        Kana { romaji: "wo", kana: "ヲ" },
        Kana { romaji: "n", kana: "ン" }
    ];
}